Limit center freq
BouchardLab/process_nwb pull request #21
Opened 2020-12-19 01:12 UTC by jthermiz

Only calculate wavelet for frequencies 2.5 times less than sample rate

2020-12-19 01:59 UTC, JesseLivezey commented
I'd advocate for a different logic here. In general, I think it's better to either do what the user asked or raise an error. Changing things behind the scenes (even if documented) would be somewhat surprising.

I'd suggest raising an error if the max cfs is above the nyqist (2x). Then, as a lab, we should use the 2.5x standard.

As is, this would break the Chang lab standard which I use for the human recordings.

2020-12-19 20:03 UTC, jthermiz commented
@JesseLivezey Sounds good. I updated it to now throw and exception with an explanation to the user if they try to compute wavelets above the Nyquist.

2020-12-21 19:21 UTC, JesseLivezey requested changes

2020-12-21 19:21 UTC, JesseLivezey commented on process_nwb/wavelet_transform.py
> +        raise Exception('Unable to compute wavelet transform above Nyquist rate.' +
```suggestion
        raise ValueError('Unable to compute wavelet transform above Nyquist rate.' +
```

2020-12-30 21:08 UTC, JesseLivezey commented
I think the failing test is actually my fault.
If you change this to `400.`, I think things should pass
https://github.com/BouchardLab/process_nwb/blob/dd086e4832a37e547588bfbbae2463c8c4becd28/tests/test_wavelet_transform.py#L20

2020-12-30 21:10 UTC, JesseLivezey commented
Actually, the fix is a little more complicated. If you fix the flake8 formatting issues, I'll make a follow up PR to fix the test.

2020-12-30 21:12 UTC, JesseLivezey commented
If you run `flake8 process_nwb tests` from the root folder, you can see the errors before you push.

2021-02-09 02:25 UTC, merged